#!/bin/bash
# Creates "Video Studio.app" in ~/Applications: a small launcher that starts the Studio server
# if it is not running and opens it in the default browser. Find it with Spotlight (⌘Space).
#   bash scripts/make-app.sh
set -euo pipefail

APP_DIR="$(cd "$(dirname "$0")/.." && pwd)"
HOME_DIR="$HOME/.video-studio"
DEST="${STUDIO_APP_DEST:-$HOME/Applications}"
BUNDLE="$DEST/Video Studio.app"
PORT="${STUDIO_PORT:-3210}"
export PATH="$HOME_DIR/node/bin:$HOME_DIR/tools/bin:$HOME_DIR/bin:$PATH"

# An app opened from Finder does not get the terminal's PATH, so the folders of the tools found
# now are written into the launcher.
TOOL_PATH="$HOME_DIR/node/bin:$HOME_DIR/tools/bin:$HOME_DIR/bin"
for t in node pnpm ffmpeg ffprobe; do
  if p="$(command -v "$t" 2>/dev/null)"; then d="$(dirname "$p")"; case ":$TOOL_PATH:" in *":$d:"*) ;; *) TOOL_PATH="$TOOL_PATH:$d" ;; esac; fi
done
TOOL_PATH="$TOOL_PATH:/usr/bin:/bin:/usr/sbin:/sbin"

mkdir -p "$BUNDLE/Contents/MacOS" "$BUNDLE/Contents/Resources" "$HOME_DIR"

cat > "$BUNDLE/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleName</key><string>Video Studio</string>
  <key>CFBundleDisplayName</key><string>Video Studio</string>
  <key>CFBundleIdentifier</key><string>local.video-studio.launcher</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>launcher</string>
  <key>CFBundleIconFile</key><string>icon</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>NSHighResolutionCapable</key><true/>
</dict></plist>
PLIST

cat > "$BUNDLE/Contents/MacOS/launcher" <<LAUNCH
#!/bin/bash
# Generated by scripts/make-app.sh — re-run that script instead of editing this file.
APP_DIR="$APP_DIR"
HOME_DIR="\$HOME/.video-studio"
URL="http://localhost:$PORT"
LOG="\$HOME_DIR/server.log"
export PATH="$TOOL_PATH"
mkdir -p "\$HOME_DIR"

up() { curl -s -o /dev/null --max-time 1 "\$URL"; }
fail() { osascript -e "display alert \"Video Studio could not start\" message \"\$1\" as critical" >/dev/null 2>&1; exit 1; }

if ! up; then
  cd "\$APP_DIR" 2>/dev/null || fail "The app folder is missing: \$APP_DIR. Run setup again (see setup.md)."
  command -v node >/dev/null && command -v pnpm >/dev/null || fail "Node or pnpm was not found. Run setup again (see setup.md)."
  if [ ! -f .next/BUILD_ID ]; then
    osascript -e 'display notification "First start: preparing the app, about a minute…" with title "Video Studio"' >/dev/null 2>&1
    pnpm build >> "\$LOG" 2>&1 || fail "The build failed. Details are in \$LOG"
  fi
  nohup pnpm start >> "\$LOG" 2>&1 &
  for _ in \$(seq 1 80); do up && break; sleep 0.5; done
  up || fail "The server did not answer on \$URL. Details are in \$LOG"
fi
open "\$URL"
LAUNCH
chmod +x "$BUNDLE/Contents/MacOS/launcher"

# icon: PNG -> .icns with the tools every Mac has
if [ -f "$APP_DIR/assets/icon.png" ]; then
  SET="$(mktemp -d)/icon.iconset"; mkdir -p "$SET"
  for s in 16 32 128 256 512; do
    sips -z $s $s "$APP_DIR/assets/icon.png" --out "$SET/icon_${s}x${s}.png" >/dev/null
    sips -z $((s*2)) $((s*2)) "$APP_DIR/assets/icon.png" --out "$SET/icon_${s}x${s}@2x.png" >/dev/null
  done
  iconutil -c icns "$SET" -o "$BUNDLE/Contents/Resources/icon.icns"
  rm -rf "$(dirname "$SET")"
fi
touch "$BUNDLE"   # makes Finder pick up the new icon
mdimport "$BUNDLE" >/dev/null 2>&1 || true   # and Spotlight find it straight away
echo "Created: $BUNDLE"
